version: '3'
services:
      mongodb:
        image: mongo:latest
        container_name: mongodb
        hostname: mongodb
        volumes:
            - ./data/:/data/db/
        ports:
            - "27017:27017"

      application:
        image: treeator/vktest
        ports:
          - "80:8070"
        env_file: 
          - .env